### PR TITLE
Replica of the Newsweek website

### PR DESCRIPTION
**Pull request by Vagyasri**
We have created the header and the footer of the Newsweek website using bootstrap and tried to make it look responsive to the three screen sizes.

Feel free to review and help us improve.

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Status: Change Requested

Amazing job so far @Vagyasri and @barackm it always brings a smile to my face to see people who work hard your project is almost done only a few changes you have to make to be ready for the next milestone

## To Highlight image

- Used bootstrap classes as requested
- Used semantic HTML
- Page looks awesome on the desktop
- Footer logo is a link
- All footer list links as requested
- README is super descriptive

## To improve image

### Header

- Newsweek logo is supposed to have a link
- Logo In tablet and mobile, it is aligned to the left
- In mobile, the Login button changes into an icon

yours on mobile

hd

original

ogn

use bootstrap classes to make it responsive to the mobile and tablet screens and on mobile,
 you don't have to show login just show an icon

- In mobile and tablet the menu hides, and show a hamburger button kindly refer to the original

burger

- The size of the elements changes in desktop, tablet, and mobile. always remember to refer to the original 
- Check where you added more padding to make the height of the page more consistent check the image
padd

This is an empty space on the footer bottom check where this is coming from

## KIndly work on that and submit another CRR and remember you still have only 2CR and work accordingly

All the best,

Lydia Ingabire

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
# Status: ♻️ Changes Required ♻️
## Hi @Vagyasri and @barackm, I'm Dipesh your reviewer for this PR.

Your clone is awesome. It looks like the exact one. Good to see that you have fixed almost all the changes told in the previous review. 👏 👏

But in order to approve we have to work on some of the changes mentioned below.

## For Approval

- [x] The last element in nav menu is going outside from the page from 992px to 1018px.

Screenshot (1290)_LI


- [x] It is super large when loads for the first time. But after reducing and again increasing it becomes very small. Please fix this issue.

### First Reload
Screenshot (1291)

### After reducing and increasing the resolution

Screenshot (1292)_LI


Fix this and Request another code review.

## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "**

Code review by **Dipesh Kumar**

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Twitter](https://twitter.com/97deepeshkumar)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Vagyasri and @barackm  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone almost looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The navbar should look like the original website on all mobile screens, unfortunately, on your clone the last elements are being cut on screens between 320px and 410px. Please learn the screenshots below to know more about that issues


| Your clone | Original page |
| --- | --- |
| Screenshot from 2021-04-06 11-36-50 | Screenshot from 2021-04-06 11-36-04 |

:point_right: Could you see the difference :question: :question: :question: 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by descholar-ceo** [comment]
@Vagyasri and @barackm _"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrmBIv6cXYrq4Fgv)."_

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @Vagyasri and @barackm  , your project is approved :tada: :tada: :tada: 

You have implemented all requested changes by the previous reviewer, so I am here to mark it as complete,

Don't forget to fill the mandatory project completion form, and see you to next project,

### Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Comment by descholar-ceo** [comment]
Hello @Vagyasri and @barackm !

I've just realized that requesting you to implement [this change](https://github.com/Vagyasri/Project3-newsweek/pull/1#pullrequestreview-628769751) was not mandatory for you because the previous reviewer did not mention it.
I am sincerely sorry to mislead you. I haven't done that on purpose :blush:

**Comment by barackm** [comment]
> Hello @Vagyasri and @barackm !
> 
> I've just realized that requesting you to implement [this change](https://github.com/Vagyasri/Project3-newsweek/pull/1#pullrequestreview-628769751) was not mandatory for you because the previous reviewer did not mention it.
> I am sincerely sorry to mislead you. I haven't done that on purpose 😊

Hi @descholar-ceo,  It's fine we do understand. however, we don't see the dashboard updated for us to submit that first milestone it still says Requested changes.

**Comment by descholar-ceo** [comment]
It will change very soon, please be patient a little bit,

**Comment by barackm** [comment]
Okay fine, Thank you!

**Comment by Dipeshtwis** [comment]
> 
> # Status: ♻️ Changes Required ♻️
> ## Hi @Vagyasri and @barackm, I'm Dipesh your reviewer for this PR.
> 
> Your clone is awesome. It looks like the exact one. Good to see that you have fixed almost all the changes told in the previous review. 👏 👏
> 
> But in order to approve we have to work on some of the changes mentioned below.
> ## For Approval
> 
>     * [x]  The last element in nav menu is going outside from the page from 992px to 1018px.
> 
> 
> Screenshot (1290)_LI
> 
>     * [x]  It is super large when loads for the first time. But after reducing and again increasing it becomes very small. Please fix this issue.
> 
> 
> ### First Reload
> 
> Screenshot (1291)
> ### After reducing and increasing the resolution
> 
> Screenshot (1292)_LI
> 
> Fix this and Request another code review.
> ## Reminder
> 
> **"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "**
> 
> Code review by **Dipesh Kumar**
> 
> (Feel free to contact me on slack by the handle of **deep** if you have any additional questions).
> Happy Coding
> [Dipesh Kumar](https://deeptwist.tk)
> [Twitter](https://twitter.com/97deepeshkumar)

Hello @Vagyasri and @barackm,

I've just realized that I did one mistake in this review and not mentioned the truncated navbar(<400px). Because of that, you went through some difficulties.

I am sincerely sorry to mislead you. I haven't done that on purpose 😊

**Pull request merged**
